# 토스 컨퍼런스.

토스팀 -> 인앱 서비스, 홈페이지, 토스페이먼츠 결제, 주식탭, 혜택탭 등.
토스 앱 안에서 WebView 로 서비스 개발하고 있습니다.

웹 서비스에서 가장 다루기 어려운 부분은 ?

비동기 프로그래밍.

순서가 보장되지 않은 경우. -> 웹 서버에 요청 -> 응답만을 기다리고 다른 인터렉션 반응 x -> 멈춰있음.
이렇게 하는 게아니라 다른 작업을 하면서 좋은 경험을 보여주다가 다시 할 일을 하는 비동기 프로그래밍 대표적으로 나타내는 작업 중 하나 입니다.

좋은 사용자 경험을 위해 필수.
Callback, Promise, RxJS  다양한 도구를 사용 해 비동기를 다루고 있습니다.





좋은 코드란 ?

함수 변수, 응집도, 느슨한 결합, 의존성의 역전 등 많은 부분에 대한 이야기.
좋은 코드에 대한 원칙 살펴보자.

하는 일은 단순하지만 코드가 너무 복잡.
-> x.foo.bar.z 에 안전하게 들어가기 -> x, foo, bar, z 각각 없는 지 검사 -> 함수가 어떤 기능을 하는 지 명확하게 드러나지 않음.

옵셔널 체이닝 문법.

``` javascript
    function getBazFrom(x) {
        return x?.foo?.bar?.bar; 
    }
```

우선 코드가 간결합니다.
어떤 역할을 하는 함수인지 함눈에 알 수 있습니다.


-> 성공하는 경우와 실패하는 경우가 전혀 나뉘어 있으면 안 됩니다.
중간에 실패하는 경우 처리가 석여서 -> 함수가 하는 진짜 역할이 모르겠습니다.

_즉 코드를 작성하는 입장에서 매 번 에러 유무를 확인해야 합니다._

``` javascript
function fetchAccounts(callback) {
    fetchUserEntity((err, user) => {
        if (err != null) {
            callback(err, null);
            return; 
        }

        fetchUserAccounts(user.no, (err, accounts) => {
            if (err != null) {
                callback(err, null);
                return; 
            }
            callback(null, accounts); 
        })
    })  
}
```


async await 문법을 사용하면 이전 코드에 비해 간결 해 집니다.
왜 좋은 코드라고 할 수 있을까요? 

1. 성공 경우만 다루고, 실패하는 경우는 catch 절에서 분리해 처리합니다 -> _덕분에 함수가 하는 역할이 명확히 드러납니다._
2. 실패하는 경우에 대한 처리를 외부에서 위임 할 수 있습니다.

``` javascript
async function fetchAccouns() {
    const user = await fetchUserEntity();
    const accouns = await fetchUserAccounts(user.no);
    return accounts; 
}
```



Hook 을 사용하여 비동기를 처리하는 부분을 정의합니다.

``` javascript
const { data, error } = useAsyncValue(() => {
    return fetchSomething(); 
})
```

Promise 를 반환하는 함수를 React Hook 의 인자로 넘기고 
Promise 상태 변화에 따라 Hook 에 상태값에 따라 error, success 를 나타 내 줍니다.





컴포넌트에서 로딩과 에러 처리를 동시에 수행한다.

``` javascript
function Profile() {
    const foo = useAsyncValue(() => {
        return fetchFoo(); 
    });

    if (foo.error) return <div>로딩 중 실패했습니다.</div>
    if (!foo.error) return <div>로딩 중 입니다...</div>
    return <div>{foo.data.name}님 안녕하세요.</div>
}
```

좋은 코드라고 보이겠지만 사실은 그렇지 않습니다.

이유는.

1. 성공하는 경우와 실패하는 경우가 섞여서 처리 됩니다.
2. 실패하는 경우에 대한 처리를 외부에 위임하기 어렵습니다.

이런 문제는 _여러 개의 비동기 작업이 같이 실행되면 더 심각 해 집니다_

`비동기 콜백 지옥`

``` javascript
function Profile() {
    const foo = useAsyncValue(() => {
        return fetchFoo(); 
    });

    const bar = useAsyncValue(() => {
        if (foo.error || !foo.data) {
            return undefined;
        }

        return fetchBar(foo.data); 
    }); 

    if (foo.error || bar.error) return <div>로딩 중 실패했습니다.</div>
    if (!foo.data || !bar.data) return <div>로딩 중 입니다...</div>
    return <div></div>
```

보통은 하나의 비동기 작업에서는 로딩 중 / 에러 / 완료 됨 -> 3가지의 상태를 가지고 있습니다.
더욱 비동기가 늘어나면 복잡 해 집니다.

즉 성공하는 경우에만 집중 해 컴포넌트를 구성하기 어렵고, 2개 이상의 비동기 로직이 개입할 떄 비즈니스 로직을 파악하기 점점 어려워 집니다.



다행이 이 문제를 해결 할 수 있는 방법이 있습니다.
방법이 _React Suspense for Data Fetching 입니다._

데이터를 가져오기 위한 SusPense 

이 방법이 목표로 하는 것.
async-await 급으로 비동기를 처리하면서 간단하고 읽기 편한 React 컴포넌트를 만들 겠다는 의미.

컴포넌트는 성공한 상태를 다루고, 로딩 상태와 에러 상태는 외부에 임의 함으로써 
동기적인 코드와 큰 차이가 없 게 만들겠다는 비젼입니다.

아래 코드를 보면 비동기와 Memo 을 사용한 동기 코드에 같이 완전히 똑같은 구조를 가지고 있는 것을 알 수 있습니다.

``` javascript
function FooBar() {
    const foo = useAsyncValue(() => fetchFoo());
    const bar = useAsyncValue(() => fetchBar(foo)); 

    return <div>{foo}{bar}</div>
}
```

``` javascript
function FooBar() {
    const foo = useMemo(() => fetchFoo());
    const bar = useMemo(() => fetchBar(foo), [foo]);

    return <div>{foo}{bar}</div>;
}
```

이러한 `useAsyncValue` 와 같은 hook 을 만들 수 있는 Low-level API 를 제공합니다.
만약? 비동기 작업을 저렇게 처리 한다면? 에러 상태나 로딩 상태는 어떻게 처리하는 게 좋을까요?



에러 상태와 로딩 상태는 어떻게 분리되는가?

``` javascript
<ErrorBoundary fallback={<MyErrorPage />}>
    <Suspense fallback={<Loader />}>
    <FooBar />
    </Suspense>
</ErrorBoundary>
```


에러 상태나 로딩 상태는 어떻게 처리해야 할까요?
함수의 에러 처리를 감싸는 catch 문에서 처리하는 것 처럼. -> 로딩 상태와 에러 처리도 컴포넌트를 쓰는 곳에서 처리 해 주면 됩니다

로딩 상태는 가장 가까운 `Suspense` 의 fallback 으로 그려지는 것.
에러 상태도 비슷하게 `ErrorBoundary` 가 처리 해 줍니다.


``` javascript
<ErrorBoundary fallback={<MyErrorPage />}>
    <Suspence fallback={<Loader />}>
        <FooBar />
    </Suspence>
</ErrorBoundary>
```

``` javascript
try {
    await fetchFooBar();
} catch (error) {
    // 에러 처리를 하는 부분. 
}
```

비동기 콜을 하는 함수나 컴포넌트가 가운데에 있고, 실패하는 경우를 처리하는 부분이 그 부분을 감싸고 있습니다.
모든 실패할 수 있는 함수에 try catch를 감싸지 않는 것 처럼 Suspence 나 ErrorBoundary 를 붙여주기 보다는 

적당한 부분 단위로 에러와 로딩상태를 한 번에 처리합니다.
이렇게 비동기를 동기적으로 바꿔주는 suspence 기능을 사용하면 됩니다.

suspence 를 사용한다고 선언 만 해주면 됩니다.

SWR, React Query -> { suspence: true }
그러면 자동으로 컴포넌트의 Suspence 상태가 관리됩니다.

suspence 를 사용하면 -> 로딩과 에러 처리를 바깥으로 위임하며 비동기 작업을 동기와 똑같이 처리할 수 있습니다.
